version: 2

build:
    image: latest
    apt_packages:
      - graphviz


python:
  version: 3.8
  install:
    - method: setuptools
      path: .
    - requirements: docs/source/requirements.txt
    - requirements: requirements.txt

formats:
  - htmlzip
  - pdf
