version: 2

formats:
  - htmlzip

build:
    os: ubuntu-22.04
    tools:
      python: "3.9"

python:
  install:
    - requirements: docs/source/requirements.txt
    - requirements: requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - d
