version: 2

build:
    image: latest
    apt_packages:
      - graphviz
    os: ubuntu-22.04
    tools:
      python: "3.8"

python:
  install:
    - requirements: docs/source/requirements.txt
    - requirements: requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - d

formats:
  - htmlzip
  - pdf
