name: Upload Python Package to PyPi

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build Python Package
    runs-on: ubuntu-latest
    steps:
    - name: get latest release with tag
      id: latestrelease
      run: |
        echo "releasetag=$(curl -s https://api.github.com/repos/AdamAdli/pyrekordbox/releases/latest --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq '.tag_name' | sed 's/\"//g')"  >> $GITHUB_ENV

    - name: confirm release tag
      run: |
        echo "${{ env.releasetag }}"

    - name: checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ env.releasetag }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.8"

    - name: Install PDM
      run: |
        python -m pip install --upgrade pip
        pip install pdm

    - name: Build distribution 📦
      run: |
        pdm build

    - uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/

  publish-test-pypi:
    name: Publish Python Package to Test-PyPi
    runs-on: ubuntu-latest
    needs: build
    environment: test-pypi
    permissions:
      id-token: write
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist

    - name: Publish package distributions 📦 to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

  publish-pypi:
    name: Publish Python Package to PyPi
    runs-on: ubuntu-latest
    needs: publish-test-pypi
    environment: pypi
    permissions:
      id-token: write
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist

    - name: Publish package distributions 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1